import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { FaBan, FaCheck, FaExchangeAlt, FaRedo, FaTimes, FaTrashAlt, FaUserShield } from 'react-icons/fa';

const API=import.meta.env.VITE_API_URL;

// Presents owner-controlled account, invitation, transfer, and security-event administration.
export default function AccountManagement({ onClose }) {
  const [data,setData]=useState({ users:[],invitations:[],securityEvents:[] }); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState('');
  const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [transferTarget,setTransferTarget]=useState(''); const [transferCode,setTransferCode]=useState(''); const [transferStarted,setTransferStarted]=useState(false);

  // Reloads current account lifecycle and security records from the server.
  const load=async () => { setLoading(true); setError(''); try { const response=await axios.get(`${API}/api/v1/accounts`); setData(response.data); } catch(requestError) { setError(requestError.response?.data?.message || 'CineVault could not load account management'); } finally { setLoading(false); } };
  useEffect(() => { load(); },[]);

  // Applies one confirmed member lifecycle operation.
  const updateAccount=async (user,action) => {
    const descriptions={ disable:'disable access for',activate:'restore access for',restore:'cancel scheduled deletion for','permanent-delete':'permanently delete' };
    if (!window.confirm(`CineVault will ${descriptions[action]} ${user.displayName}. Continue?`)) return;
    setBusy(`${user.id}:${action}`); setError(''); try { const response=await axios.patch(`${API}/api/v1/accounts/${user.id}`,{ action }); setMessage(response.data.message); await load(); } catch(requestError) { setError(requestError.response?.data?.message || 'The account action failed'); } finally { setBusy(''); }
  };

  // Revokes one pending invitation after owner confirmation.
  const revoke=async (invitation) => { if (!window.confirm(`Revoke the pending invitation for ${invitation.email}?`)) return; setBusy(`invite:${invitation.id}`); try { const response=await axios.delete(`${API}/api/v1/accounts/invitations/${invitation.id}`); setMessage(response.data.message); await load(); } catch(requestError) { setError(requestError.response?.data?.message || 'The invitation could not be revoked'); } finally { setBusy(''); } };

  // Requests a mailbox code before transferring the owner role.
  const requestTransfer=async () => { if (!transferTarget) return; const target=data.users.find((user) => user.id === transferTarget); if (!window.confirm(`Transfer CineVault ownership to ${target?.displayName}? Your account will become a member.`)) return; setBusy('transfer-request'); try { const response=await axios.post(`${API}/api/v1/accounts/ownership/request`,{ targetUserId:transferTarget }); setTransferStarted(true); setMessage(response.data.message); } catch(requestError) { setError(requestError.response?.data?.message || 'Ownership transfer could not be started'); } finally { setBusy(''); } };

  // Completes the ownership transfer using the current owner's mailbox code.
  const confirmTransfer=async () => { setBusy('transfer-confirm'); try { const response=await axios.post(`${API}/api/v1/accounts/ownership/confirm`,{ verificationCode:transferCode }); setMessage(response.data.message); setTransferStarted(false); setTransferCode(''); window.setTimeout(() => window.location.reload(),1200); } catch(requestError) { setError(requestError.response?.data?.message || 'Ownership transfer could not be completed'); } finally { setBusy(''); } };

  const pendingInvitations=data.invitations.filter((item) => !item.acceptedAt);
  return <div className="content-area account-management"><section className="management-heading"><div><span className="eyebrow">PRIVATE ACCESS CONTROL</span><h2><FaUserShield/> Accounts & security</h2><p>Manage members, delivery status, scheduled deletion, ownership and recent authentication activity.</p></div><button type="button" onClick={onClose} title="Return to the library" aria-label="Return to library"><FaTimes/></button></section>
    {error && <p className="field-error" role="alert">{error}</p>}{message && <p className="field-success" role="status">{message}</p>}
    {loading ? <div className="empty-state" aria-busy="true">Loading account security…</div> : <>
      <section className="management-panel"><h3>Accounts</h3><div className="account-list">{data.users.map((user) => <article key={user.id} className="account-row"><div><strong>{user.displayName}</strong><span>{user.email}</span><small>{user.role} · {user.deletionScheduledAt ? `deletion scheduled ${new Date(user.deletionScheduledAt).toLocaleString()}` : user.status}{user.lastLoginAt ? ` · last sign-in ${new Date(user.lastLoginAt).toLocaleString()}` : ''}</small></div>{user.role !== 'owner' && <div className="account-actions">{user.deletionScheduledAt ? <><button disabled={Boolean(busy)} aria-busy={busy === `${user.id}:restore`} onClick={() => updateAccount(user,'restore')} title="Cancel scheduled deletion and restore account access"><FaRedo/> {busy === `${user.id}:restore` ? 'Restoring…' : 'Restore'}</button><button className="danger-action" disabled={Boolean(busy)} aria-busy={busy === `${user.id}:permanent-delete`} onClick={() => updateAccount(user,'permanent-delete')} title="Immediately and permanently remove this account and its library"><FaTrashAlt/> {busy === `${user.id}:permanent-delete` ? 'Deleting…' : 'Delete now'}</button></> : user.status === 'active' ? <button disabled={Boolean(busy)} aria-busy={busy === `${user.id}:disable`} onClick={() => updateAccount(user,'disable')} title="Block sign-in without deleting the library"><FaBan/> {busy === `${user.id}:disable` ? 'Disabling…' : 'Disable'}</button> : <button disabled={Boolean(busy)} aria-busy={busy === `${user.id}:activate`} onClick={() => updateAccount(user,'activate')} title="Restore sign-in access"><FaCheck/> {busy === `${user.id}:activate` ? 'Activating…' : 'Activate'}</button>}</div>}</article>)}</div></section>
      <section className="management-panel"><h3>Pending invitations</h3>{pendingInvitations.length ? <div className="account-list">{pendingInvitations.map((invitation) => <article key={invitation.id} className="account-row"><div><strong>{invitation.email}</strong><small>Delivery: {invitation.deliveryStatus} · expires {new Date(invitation.expiresAt).toLocaleString()}</small></div><button disabled={Boolean(busy)} aria-busy={busy === `invite:${invitation.id}`} onClick={() => revoke(invitation)} title="Invalidate this invitation immediately"><FaTrashAlt/> {busy === `invite:${invitation.id}` ? 'Revoking…' : 'Revoke'}</button></article>)}</div> : <p className="management-empty">No pending invitations.</p>}</section>
      <section className="management-panel"><h3>Transfer ownership</h3><p>The current owner receives a 10-minute verification code. Both accounts are notified after completion.</p><div className="transfer-controls"><select value={transferTarget} disabled={transferStarted || Boolean(busy)} onChange={(event) => setTransferTarget(event.target.value)} title="Choose the active member who should become owner"><option value="">Choose an active member</option>{data.users.filter((user) => user.role === 'member' && user.status === 'active').map((user) => <option key={user.id} value={user.id}>{user.displayName} — {user.email}</option>)}</select>{!transferStarted ? <button className="secondary-action" disabled={!transferTarget || Boolean(busy)} aria-busy={busy === 'transfer-request'} onClick={requestTransfer}><FaExchangeAlt/> {busy === 'transfer-request' ? 'Sending code…' : 'Send transfer code'}</button> : <><input inputMode="numeric" maxLength="6" pattern="[0-9]{6}" value={transferCode} onChange={(event) => setTransferCode(event.target.value.replace(/\D/g,'').slice(0,6))} placeholder="6-digit code" aria-label="Ownership transfer verification code"/><button className="primary-action" disabled={transferCode.length !== 6 || Boolean(busy)} aria-busy={busy === 'transfer-confirm'} onClick={confirmTransfer}>{busy === 'transfer-confirm' ? 'Transferring…' : 'Confirm ownership transfer'}</button></>}</div></section>
      <section className="management-panel"><h3>Recent security activity</h3><div className="security-event-list">{data.securityEvents.map((event) => <div key={event.id}><strong>{event.action}</strong><span>{event.actor} · {event.outcome}</span><time>{new Date(event.createdAt).toLocaleString()}</time></div>)}</div></section>
    </>}
  </div>;
}
