import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { FaCheck,FaChevronRight,FaFileImport,FaHeartbeat,FaSync,FaTimes } from 'react-icons/fa';

const API=import.meta.env.VITE_API_URL;

// Presents actionable metadata checks, reviewed imports, and explicit media scans.
export default function DataHealth({ onOpen }) {
  const [report,setReport]=useState(null);
  const [message,setMessage]=useState('');
  const [importPayload,setImportPayload]=useState(null);
  const [preview,setPreview]=useState(null);
  const [decisions,setDecisions]=useState({});
  const [companyChoices,setCompanyChoices]=useState({});
  const [canonicalChoices,setCanonicalChoices]=useState({});
  const load=() => axios.get(`${API}/api/v1/data-health`).then((response) => setReport(response.data)).catch(() => setMessage('The data-health report could not be loaded.'));
  useEffect(() => {
    let active=true;
    axios.get(`${API}/api/v1/data-health`).then((response) => { if (active) setReport(response.data); })
      .catch(() => { if (active) setMessage('The data-health report could not be loaded.'); });
    return () => { active=false; };
  },[]);
  const scan=async () => { setMessage('Checking external posters and trailers…'); await axios.post(`${API}/api/v1/session/connect`,{ force:true }); setMessage('Media check started. Confirmed problems will appear in Notifications.'); };
  const openTitle=(event,id) => { event.preventDefault(); event.stopPropagation(); onOpen(id); };
  const chooseImport=async (event) => { try { const payload=JSON.parse(await event.target.files[0].text()); const response=await axios.post(`${API}/api/v1/import/preview`,payload); setImportPayload(payload); setPreview(response.data); setDecisions(Object.fromEntries(response.data.items.filter((item) => item.conflict).map((item) => [item.importId,'skip']))); setMessage(`${response.data.newItems} new titles and ${response.data.conflicts} conflicts are ready for review.`); } catch(error) { setMessage(error.response?.data?.message || 'That file is not a valid CineVault export.'); } };
  const applyImport=async () => { if (!window.confirm(`Import ${preview.total} reviewed titles? A recovery backup will be created first.`)) return; try { const response=await axios.post(`${API}/api/v1/import/apply`,{ payload:importPayload,decisions }); setMessage(`Import complete: ${response.data.added} added, ${response.data.merged} merged, ${response.data.replaced} replaced and ${response.data.skipped} kept. Backup: ${response.data.backup}`); setPreview(null); setImportPayload(null); load(); } catch(error) { setMessage(error.response?.data?.message || 'Import could not be completed.'); } };
  const mergeCompanies=async (group) => { const choice=companyChoices[group.key] || {}; const keepId=choice.keepId || group.companies[0].id; const preferredName=(choice.name || group.preferred).trim(); if (!window.confirm(`Merge these spellings into “${preferredName}”? A recovery backup will be created first.`)) return; try { const response=await axios.post(`${API}/api/v1/data-health/production-companies/merge`,{ keepId,mergeIds:group.companies.filter((company) => company.id !== keepId).map((company) => company.id),preferredName }); setMessage(`${response.data.message}. ${response.data.affectedTitles} title links updated. Backup: ${response.data.backup}`); load(); } catch(error) { setMessage(error.response?.data?.message || 'The company names could not be merged.'); } };
  const dismissCompanyGroup=async (group) => { try { await axios.post(`${API}/api/v1/data-health/production-companies/${encodeURIComponent(group.key)}/dismiss`); setMessage('Suggestion dismissed. The company records were left unchanged.'); load(); } catch(error) { setMessage(error.response?.data?.message || 'The suggestion could not be dismissed.'); } };
  const mergeCanonical=async (group) => { const choice=canonicalChoices[`${group.category}:${group.key}`] || group.preferred; if (!window.confirm(`Use “${choice}” for every listed ${group.label.toLowerCase()} variant? A recovery backup will be created first.`)) return; try { const response=await axios.post(`${API}/api/v1/data-health/canonical-values/merge`,{ category:group.category,preferred:choice,variants:group.variants.map((variant) => variant.value) }); setMessage(`${response.data.message}. Backup: ${response.data.backup}`); load(); } catch(error) { setMessage(error.response?.data?.message || 'The metadata spellings could not be merged.'); } };
  if (!report) return <section className="content-area"><div className="empty-state">{message || 'Reviewing library data…'}</div></section>;
  const checks=Object.entries(report.checks).filter(([key]) => !['companySuggestions','canonicalSuggestions'].includes(key));
  return <section className="content-area health-page">
    <header className="health-hero"><div><span className="eyebrow">LIBRARY CARE</span><h2>Data health</h2><p>Review incomplete metadata and maintenance tasks without leaving your library.</p></div><div className="health-actions"><label className="secondary-action import-button"><FaFileImport /> Import JSON<input type="file" accept="application/json,.json" onChange={chooseImport} /></label><button className="secondary-action" onClick={load}><FaSync /> Refresh</button><button className="primary-action" onClick={scan}><FaHeartbeat /> Check media links</button></div></header>
    {message && <p className="health-message" role="status">{message}</p>}
    {preview && <section className="import-preview"><h3>Import preview</h3><p>{preview.newItems} new · {preview.conflicts} conflicts · {preview.total} total</p>{preview.items.filter((item) => item.conflict).map((item) => <label key={item.importId}><span>{item.title} {item.releaseDate && `(${item.releaseDate.slice(0,4)})`}</span><select value={decisions[item.importId]} onChange={(event) => setDecisions((current) => ({ ...current,[item.importId]:event.target.value }))}><option value="skip">Keep existing</option><option value="merge">Merge histories and classifications</option><option value="replace">Replace with imported entry</option></select></label>)}<button className="primary-action" onClick={applyImport}>Apply reviewed import</button></section>}
    <div className="health-grid">{checks.map(([key,check]) => <details className="health-card" key={key}><summary><span><strong>{check.count}</strong><small>items</small></span><h3>{check.label}</h3><FaChevronRight /></summary>{check.items?.length > 0 ? <div className="health-items">{check.items.slice(0,20).flatMap((item,index) => item.id ? [<button type="button" key={item.id} onClick={(event) => openTitle(event,item.id)}><span>{item.title}</span><FaChevronRight /></button>] : item.items ? item.items.map((title) => <button type="button" key={title.id} onClick={(event) => openTitle(event,title.id)}><span>{title.title}</span><FaChevronRight /></button>) : [<span key={index}>{item.titles}</span>])}</div> : <p className="health-clear">Nothing needs attention.</p>}</details>)}</div>
    {report.checks.companySuggestions.length > 0 && <section className="company-review"><span className="eyebrow">REVIEW AND CONFIRM</span><h3>Possible company-name duplicates</h3><p>Choose the canonical record and full stored name. Merging preserves every former spelling as a searchable alias and creates a recovery backup.</p><div className="company-review-list">{report.checks.companySuggestions.slice(0,20).map((group) => { const choice=companyChoices[group.key] || {}; const keepId=choice.keepId || group.companies[0].id; return <article key={group.key} className="company-review-card"><label>Canonical record<select value={keepId} onChange={(event) => { const company=group.companies.find((item) => item.id === event.target.value); setCompanyChoices((current) => ({ ...current,[group.key]:{ ...current[group.key],keepId:event.target.value,name:company.name } })); }}>{group.companies.map((company) => <option key={company.id} value={company.id}>{company.name} · {company.uses} title{company.uses === 1 ? '' : 's'}</option>)}</select></label><label>Full stored name<input value={choice.name ?? group.preferred} onChange={(event) => setCompanyChoices((current) => ({ ...current,[group.key]:{ ...current[group.key],keepId,name:event.target.value } }))} /></label><div className="company-variants">{group.companies.map((company) => <section key={company.id}><strong>{company.name}</strong><small>{company.uses} linked title{company.uses === 1 ? '' : 's'}</small>{company.titles.map((title) => <button type="button" key={title.id} onClick={(event) => openTitle(event,title.id)}>{title.title}<FaChevronRight /></button>)}</section>)}</div><footer><button type="button" className="secondary-action" onClick={() => dismissCompanyGroup(group)}><FaTimes /> Keep separate</button><button type="button" className="primary-action" onClick={() => mergeCompanies(group)}><FaCheck /> Merge aliases</button></footer></article>; })}</div></section>}
    {report.checks.canonicalSuggestions?.length > 0 && <section className="company-review"><span className="eyebrow">SPELLING CONSISTENCY</span><h3>Review metadata variants</h3><p>These provider, network, and credit names differ only by spacing, punctuation, or capitalization. Nothing is changed without your confirmation.</p><div className="company-review-list">{report.checks.canonicalSuggestions.map((group) => { const choiceKey=`${group.category}:${group.key}`; return <article className="company-review-card" key={choiceKey}><h4>{group.label}</h4><label>Canonical spelling<select value={canonicalChoices[choiceKey] || group.preferred} onChange={(event) => setCanonicalChoices((current) => ({ ...current,[choiceKey]:event.target.value }))}>{group.variants.map((variant) => <option key={variant.value} value={variant.value}>{variant.value} · {variant.count} use{variant.count === 1 ? '' : 's'}</option>)}</select></label><div className="company-variants">{group.variants.map((variant) => <section key={variant.value}><strong>{variant.value}</strong><small>{variant.count} occurrence{variant.count === 1 ? '' : 's'}</small>{variant.titles.map((title) => <button type="button" key={title.id} onClick={(event) => openTitle(event,title.id)}>{title.title}<FaChevronRight /></button>)}</section>)}</div><footer><button type="button" className="primary-action" onClick={() => mergeCanonical(group)}><FaCheck /> Apply canonical spelling</button></footer></article>; })}</div></section>}
  </section>;
}
