import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { FaCheck,FaChevronRight,FaFileImport,FaHeartbeat,FaSync,FaTimes } from 'react-icons/fa';

const API=import.meta.env.VITE_API_URL;

// Presents actionable metadata checks, reviewed imports, and explicit media scans.
export default function DataHealth({ onOpen }) {
  const [report,setReport]=useState(null);
  const [message,setMessage]=useState('');
  const [importPayload,setImportPayload]=useState(null);
  const [preview,setPreview]=useState(null);
  const [importStrategy,setImportStrategy]=useState('add-new');
  const [companyChoices,setCompanyChoices]=useState({});
  const [canonicalChoices,setCanonicalChoices]=useState({});
  const load=() => axios.get(`${API}/api/v1/data-health`).then((response) => setReport(response.data)).catch(() => setMessage('The data-health report could not be loaded.'));
  useEffect(() => {
    let active=true;
    axios.get(`${API}/api/v1/data-health`).then((response) => { if (active) setReport(response.data); })
      .catch(() => { if (active) setMessage('The data-health report could not be loaded.'); });
    return () => { active=false; };
  },[]);
  const scan=async () => { setMessage('Checking external posters and trailers…'); await axios.post(`${API}/api/v1/session/connect`,{ force:true }); setMessage('Media check started. Confirmed problems will appear in Notifications.'); };
  const openTitle=(event,id) => { event.preventDefault(); event.stopPropagation(); onOpen(id); };
  const chooseImport=async (event) => { try { const payload=JSON.parse(await event.target.files[0].text()); const response=await axios.post(`${API}/api/v1/import/preview`,payload); setImportPayload(payload); setPreview(response.data); setImportStrategy('add-new'); setMessage(`${response.data.validItems} valid titles and ${response.data.invalidItems} invalid titles were found. Review the report before importing.`); } catch(error) { setMessage(error.response?.data?.message || 'That file is not a valid CineVault export.'); } finally { event.target.value=''; } };
  const cancelImport=() => { setPreview(null); setImportPayload(null); setImportStrategy('add-new'); setMessage('Import canceled. No library data was changed.'); };
  const applyImport=async () => { const replacing=importStrategy === 'replace-library'; let subsetConfirmation=''; if (replacing && preview.isSubset) { subsetConfirmation=window.prompt(`This is a partial “${preview.scope}” export containing ${preview.total} titles. Replacing will permanently remove every current title not present in this subset after creating a recovery backup.\n\nType REPLACE WITH SUBSET to continue:`) || ''; if (subsetConfirmation !== 'REPLACE WITH SUBSET') { if (subsetConfirmation) setMessage('The confirmation phrase did not match. No library data was changed.'); return; } } else { const prompt=replacing ? `Replace the entire current library and Trash with all ${preview.total} imported titles? A verified recovery backup is created first. Invalid titles must be corrected before replacement.` : `Keep the current database and add ${preview.newItems} new validated titles? ${preview.conflicts} matching titles will remain unchanged and ${preview.invalidItems} invalid titles will be excluded.`; if (!window.confirm(prompt)) return; } try { const response=await axios.post(`${API}/api/v1/import/apply`,{ payload:importPayload,strategy:importStrategy,mode:replacing ? 'all' : 'valid-only',subsetConfirmation }); setMessage(replacing ? `Library replaced with ${response.data.added} active titles. Recovery backup: ${response.data.backup}` : `Import complete: ${response.data.added} new titles added, ${response.data.skipped} existing matches kept, and ${response.data.skippedInvalid} invalid titles excluded. Backup: ${response.data.backup}`); setPreview(null); setImportPayload(null); load(); } catch(error) { setMessage(`${error.response?.data?.message || 'Import could not be completed.'} No titles from this attempt were imported.`); } };
  const mergeCompanies=async (group) => { const choice=companyChoices[group.key] || {}; const keepId=choice.keepId || group.companies[0].id; const preferredName=(choice.name || group.preferred).trim(); if (!window.confirm(`Merge these spellings into “${preferredName}”? A recovery backup will be created first.`)) return; try { const response=await axios.post(`${API}/api/v1/data-health/production-companies/merge`,{ keepId,mergeIds:group.companies.filter((company) => company.id !== keepId).map((company) => company.id),preferredName }); setMessage(`${response.data.message}. ${response.data.affectedTitles} title links updated. Backup: ${response.data.backup}`); load(); } catch(error) { setMessage(error.response?.data?.message || 'The company names could not be merged.'); } };
  const dismissCompanyGroup=async (group) => { try { await axios.post(`${API}/api/v1/data-health/production-companies/${encodeURIComponent(group.key)}/dismiss`); setMessage('Suggestion dismissed. The company records were left unchanged.'); load(); } catch(error) { setMessage(error.response?.data?.message || 'The suggestion could not be dismissed.'); } };
  const mergeCanonical=async (group) => { const choice=canonicalChoices[`${group.category}:${group.key}`] || group.preferred; if (!window.confirm(`Use “${choice}” for every listed ${group.label.toLowerCase()} variant? A recovery backup will be created first.`)) return; try { const response=await axios.post(`${API}/api/v1/data-health/canonical-values/merge`,{ category:group.category,preferred:choice,variants:group.variants.map((variant) => variant.value) }); setMessage(`${response.data.message}. Backup: ${response.data.backup}`); load(); } catch(error) { setMessage(error.response?.data?.message || 'The metadata spellings could not be merged.'); } };
  if (!report) return <section className="content-area"><div className="empty-state">{message || 'Reviewing library data…'}</div></section>;
  const checks=Object.entries(report.checks).filter(([key]) => !['companySuggestions','canonicalSuggestions'].includes(key));
  return <section className="content-area health-page">
    <header className="health-hero"><div><span className="eyebrow">LIBRARY CARE</span><h2>Data health</h2><p>Review incomplete metadata and maintenance tasks without leaving your library.</p></div><div className="health-actions"><label className="secondary-action import-button"><FaFileImport /> Import JSON<input type="file" accept="application/json,.json" onChange={chooseImport} /></label><button className="secondary-action" onClick={load}><FaSync /> Refresh</button><button className="primary-action" onClick={scan}><FaHeartbeat /> Check media links</button></div></header>
    {message && <p className="health-message" role="status">{message}</p>}
    {preview && <section className="import-preview"><span className="eyebrow">{preview.exportType === 'clean' ? 'CLEAN TRANSFER' : 'COMPLETE RECOVERY'} · {preview.scope}{preview.isSubset ? ' · PARTIAL EXPORT' : ' · FULL LIBRARY'}</span><h3>Import validation</h3><p>{preview.validItems} valid · {preview.invalidItems} invalid · {preview.conflicts} existing matches · {preview.total} total</p>{preview.items.filter((item) => !item.valid).map((item) => <article className="import-warning" key={`invalid-${item.importId}`}><strong>{item.title}</strong>{item.issues.map((issue) => <small key={issue}>{issue}</small>)}</article>)}<div className="import-strategies" role="radiogroup" aria-label="Import strategy"><label className="export-choice"><input type="radio" name="import-strategy" value="add-new" checked={importStrategy === 'add-new'} onChange={() => setImportStrategy('add-new')} /><span><strong>Keep existing and add new</strong><small>Adds only titles whose content type, normalized title, and release date do not already exist. Matching active or trashed entries remain unchanged.</small></span></label><label className="export-choice"><input type="radio" name="import-strategy" value="replace-library" checked={importStrategy === 'replace-library'} onChange={() => setImportStrategy('replace-library')} /><span><strong>Replace current library</strong><small>After a verified backup, removes the current Library and Trash and reconstructs them from this file. Every imported title is restored as active.{preview.isSubset ? ' Because this is a partial export, typed confirmation will be required.' : ''}</small></span></label></div>{importStrategy === 'replace-library' && preview.invalidItems > 0 && <p className="import-warning"><strong>Replacement is unavailable</strong><small>Correct all invalid entries in the export before replacing the database.</small></p>}<footer className="import-actions"><button className="secondary-action" type="button" onClick={cancelImport}>Cancel · import nothing</button><button className="primary-action" type="button" disabled={!preview.validItems || (importStrategy === 'replace-library' && preview.invalidItems > 0)} onClick={applyImport}>{importStrategy === 'replace-library' ? 'Replace library' : 'Add new titles'}</button></footer></section>}
    <div className="health-grid">{checks.map(([key,check]) => <details className="health-card" key={key}><summary><span><strong>{check.count}</strong><small>items</small></span><h3>{check.label}</h3><FaChevronRight /></summary>{check.items?.length > 0 ? <div className="health-items">{check.items.slice(0,20).flatMap((item,index) => item.id ? [<button type="button" key={item.id} onClick={(event) => openTitle(event,item.id)}><span>{item.title}</span><FaChevronRight /></button>] : item.items ? item.items.map((title) => <button type="button" key={title.id} onClick={(event) => openTitle(event,title.id)}><span>{title.title}</span><FaChevronRight /></button>) : [<span key={index}>{item.titles}</span>])}</div> : <p className="health-clear">Nothing needs attention.</p>}</details>)}</div>
    {report.checks.companySuggestions.length > 0 && <section className="company-review"><span className="eyebrow">REVIEW AND CONFIRM</span><h3>Possible company-name duplicates</h3><p>Choose the canonical record and full stored name. Merging preserves every former spelling as a searchable alias and creates a recovery backup.</p><div className="company-review-list">{report.checks.companySuggestions.slice(0,20).map((group) => { const choice=companyChoices[group.key] || {}; const keepId=choice.keepId || group.companies[0].id; return <article key={group.key} className="company-review-card"><label>Canonical record<select value={keepId} onChange={(event) => { const company=group.companies.find((item) => item.id === event.target.value); setCompanyChoices((current) => ({ ...current,[group.key]:{ ...current[group.key],keepId:event.target.value,name:company.name } })); }}>{group.companies.map((company) => <option key={company.id} value={company.id}>{company.name} · {company.uses} title{company.uses === 1 ? '' : 's'}</option>)}</select></label><label>Full stored name<input value={choice.name ?? group.preferred} onChange={(event) => setCompanyChoices((current) => ({ ...current,[group.key]:{ ...current[group.key],keepId,name:event.target.value } }))} /></label><div className="company-variants">{group.companies.map((company) => <section key={company.id}><strong>{company.name}</strong><small>{company.uses} linked title{company.uses === 1 ? '' : 's'}</small>{company.titles.map((title) => <button type="button" key={title.id} onClick={(event) => openTitle(event,title.id)}>{title.title}<FaChevronRight /></button>)}</section>)}</div><footer><button type="button" className="secondary-action" onClick={() => dismissCompanyGroup(group)}><FaTimes /> Keep separate</button><button type="button" className="primary-action" onClick={() => mergeCompanies(group)}><FaCheck /> Merge aliases</button></footer></article>; })}</div></section>}
    {report.checks.canonicalSuggestions?.length > 0 && <section className="company-review"><span className="eyebrow">SPELLING CONSISTENCY</span><h3>Review metadata variants</h3><p>These provider, network, and credit names differ only by spacing, punctuation, or capitalization. Nothing is changed without your confirmation.</p><div className="company-review-list">{report.checks.canonicalSuggestions.map((group) => { const choiceKey=`${group.category}:${group.key}`; return <article className="company-review-card" key={choiceKey}><h4>{group.label}</h4><label>Canonical spelling<select value={canonicalChoices[choiceKey] || group.preferred} onChange={(event) => setCanonicalChoices((current) => ({ ...current,[choiceKey]:event.target.value }))}>{group.variants.map((variant) => <option key={variant.value} value={variant.value}>{variant.value} · {variant.count} use{variant.count === 1 ? '' : 's'}</option>)}</select></label><div className="company-variants">{group.variants.map((variant) => <section key={variant.value}><strong>{variant.value}</strong><small>{variant.count} occurrence{variant.count === 1 ? '' : 's'}</small>{variant.titles.map((title) => <button type="button" key={title.id} onClick={(event) => openTitle(event,title.id)}>{title.title}<FaChevronRight /></button>)}</section>)}</div><footer><button type="button" className="primary-action" onClick={() => mergeCanonical(group)}><FaCheck /> Apply canonical spelling</button></footer></article>; })}</div></section>}
  </section>;
}
